name: Build Kernel With Custom Toolchain

on:
  workflow_dispatch:
    inputs:
      CLANG_AOSP:
        description: 'Clang url with tar.gz format'
        required: true
        default: ''
      GCC_AOSP:
        description: 'GCC url with tar.gz format'
        required: true
        default: ''
      
jobs:
  building kernel:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Start Building Rookie Kernel
        run: |
          cd ${GITHUB_WORKSPACE}
          export KBUILD_BUILD_USER="${{ github.actor }}"
          export KBUILD_BUILD_HOST="${{ github.event.inputs.DEVICE_NAME }}"
          chmod +x build_kernel.sh
          ./build_kernel.sh

      - name: Set Properties
        id: props
        run: |
          echo "date=$(TZ=Asia/Jakarta date +%Y%m%d-%I%M%p)" >> $GITHUB_OUTPUT
       
      - name: Make Zip
        run: |
          cd ${GITHUB_WORKSPACE}
          export DEVICE_NAME=SM-A022F
          zip -r9 ${DEVICE_NAME}-${{ steps.props.outputs.date }}.zip boot.img-kernel
        
      - name: Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: |
            ${{ github.workspace }}/*.zip
          name: Compiled Kernel for SM-A022F - ${{ steps.props.outputs.date }}
          draft: false
          prerelease: false
          tag: ${{ github.run_id }}-${{ steps.props.outputs.date }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ## Notes
              - Kernel for SM-A022F, ready to download.
      
      - name: Link of Release
        run: |
          echo "Enjoy your Newly Built Kernel"
          echo "https://github.com/${GITHUB_REPOSITORY}/releases/tag/${{ github.run_id }}-${{ steps.props.outputs.date }}"     
