name: Build Kernel

on: workflow_dispatch

jobs:
  run-script-file-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Start Building Rookie Kernel
        run: |
          cd ${GITHUB_WORKSPACE}
          export KBUILD_BUILD_USER="${{ github.actor }}"
          export KBUILD_BUILD_HOST="${{ github.event.inputs.DEVICE_NAME }}"
          chmod +x build_kernel.sh
          ./build_kernel.sh

      - name: Set Properties
        id: props
        run: |
          echo "date=$(TZ=Asia/Jakarta date +%Y%m%d-%I%M%p)" >> $GITHUB_OUTPUT
       
      - name: Make Zip
        run: |
          cd ${GITHUB_WORKSPACE}
          cd out/arch/arm/boot
          ls
          export DEVICE_NAME=SM-A022F
          zip -r9 ${DEVICE_NAME}-${{ steps.props.outputs.date }}.zip *
        
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
        
      - name: Add and Commit file
        run: |
          git add -A
          git commit -m "Ready to download"
          git push
        
      - name: Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: |
            ${{ github.workspace }}/*.zip
          name: Compiled Kernel for SM-A022F - ${{ steps.props.outputs.date }}
          draft: false
          prerelease: false
          tag: ${{ github.run_id }}-${{ steps.props.outputs.date }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ## Notes
              - Extract ${DEVICE_NAME}-${{ steps.props.outputs.date }}.zip, look your newly-compiled kernel inside.
              - Include building logs.
      
      - name: Link of Release
        run: |
          echo "Enjoy your Newly Built Kernel"
          echo "https://github.com/${GITHUB_REPOSITORY}/releases/tag/${{ github.run_id }}-${{ steps.props.outputs.date }}"     
        
