name: Tes doang

on:
  workflow_dispatch:

jobs:
  making-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Nyoba
      run: |
        cd ${GITHUB_WORKSPACE}
        git clone https://github.com/manteiga25/rainbow-kernel-samsung-a12 -b main
        mkdir -p tempe
        ls
        echo ------------bentar------------
        cp -r rainbow-kernel-samsung-a12/drivers/input/touchscreen/ili9881x/* tempe
        ls
        echo ------------bentar------------
        cd tempe
        ls
        echo ------------bentar------------
        cd ili9881x
        ls
        
