name: Create ZIP

on:
  workflow_dispatch:

jobs:
  making-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set Properties
      id: props
      run: |
        echo "date=$(TZ=Asia/Jakarta date +%Y%m%d-%I%M%p)" >> $GITHUB_OUTPUT
        
    - name: Coba ganti nama folder
      run: |
        cd ${GITHUB_WORKSPACE}
        export DEVICE_NAME="${SM-A022F}"
        zip -r9 ${DEVICE_NAME}-${{ steps.props.outputs.date }}.zip boot.img-kernel
        
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        
    - name: Add and Commit file
      run: |
        git add *
        git commit -m "Savage"
        git push
        
    - name: Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: |
          ${GITHUB_WORKSPACE}/*.zip
          ${GITHUB_WORKSPACE}/build.log
        name: Compiled Kernel for ${DEVICE_NAME} - ${{ steps.props.outputs.date }}
        draft: false
        prerelease: false
        tag: ${{ github.run_id }}-${{ steps.props.outputs.date }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ## Notes
            - Extract ${DEVICE_NAME}-${{ steps.props.outputs.date }}.zip, look your newly-compiled kernel inside.
            - Include building logs.
      
    - name: Link of Release
      run: |
        echo "Enjoy your Newly Built Kernel"
        echo "https://github.com/${GITHUB_REPOSITORY}/releases/tag/${{ github.run_id }}-${{ steps.props.outputs.date }}"     
